baseURL = 'https://aegon007.github.io/'
languageCode = 'en-us'
title = 'Chenggang Wang Homepage'
#theme = 'recover'

# Sample params from an AA group format

[params]
    name = "Chenggang Wang"
    description = "Chenggang Wang is an Assistant Professor at the University of Oklahoma researching data security, privacy, networks, and trustworthy computing."
    selfImage = "/images/self.jpg"

    position = "Assistant Professor"
    affliation = "Polytechnic Institute"
    university = "University of Oklahoma"
    address = "Tulsa, Oklahoma, 74135"

    phone = "+1.918.660.3183"
    email = "chenggang.wang@ou.edu"

    cv = "https://www.linkedin.com/in/carlwang007/"
    github = "https://github.com/users/Aegon007/projects/1"
    google_scholar = "https://scholar.google.com/citations?user=nvAQ5LwAAAAJ&hl=en"

    lab_name = "Cipher Lab"
    lab_intro = "Our lab is focused on next generation trustable and secure computing systems"

[menu]
 [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
 [[menu.main]]
    name = "Biography"
    url = "/bio"
    weight = 2
 [[menu.main]]
    name = "Publications"
    url = "/pubs"
    weight = 4
 [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 5
 [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 6
 [[menu.main]]
    name = "Cipher Lab"
    url = "/lab"
    weight = 7

[module]
  [module.hugoVersion]
    extended = true
    min = ""
    max = ""

[Permalinks]
    post = "/:filename/"
