baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Chenggang Wang Homepage'
theme = 'recover'

# Sample params from an AA group format

[params]
    name = "Chenggang Wang"
    description = "A Hugo Theme enabling user to easily maintain a clean, readable academic home page."
    selfImage = "/images/self.jpg"

    position = "Assistant Professor"
    affliation = "Polytechnic Institute"
    university = "University of Oklahoma"
    address = "Tulsa, Oklahoma, 74136"

    office = "Tulsa campus main building"
    phone = "+1.334.244.5639"
    email = "chenggang.wang@ou.edu"

    cv = "https://www.linkedin.com/in/carlwang007/"
    github = "https://github.com/users/Aegon007/projects/1"
    google_scholar = "https://scholar.google.com/citations?user=nvAQ5LwAAAAJ&hl=en"

    lab_name = "Data Security and Machine Intelligence"
    lab_intro = "Our lab is focused on next generation trustable and secure computing systems"


[menu]
 [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
 [[menu.main]]
    name = "Biography"
    url = "/bio"
    weight = 2
 [[menu.main]]
    name = "Research and Projects"
    url = "/research"
    weight = 3
 [[menu.main]]
    name = "Publication"
    url = "/pubs"
    weight = 4
 [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 5
 [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 6
 [[menu.main]]
    name = "Members"
    url = "/members"
    weight = 7

[module]
  [module.hugoVersion]
    extended = true
    min = ""
    max = ""

[Permalinks]
    post = "/:filename/"
